language: node_js
install:
 - npm install
notifications:
  email: false
node_js:
  - '10'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
