sudo: false
language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
script:
- npm run build
- npm run test:coverage
after_success:
- codeclimate-test-reporter < coverage/lcov.info
- npm run semantic-release
